etc/hedgehog/nodes.csv
etc/hedgehog/nodes.csv.sample /usr/share/doc/hedgehog/examples/
etc/hedgehog/tlds.d/*
usr/bin/dsc-extractor
usr/bin/refile_and_grok
usr/share/man/man1/dsc-extractor.1
usr/share/man/man1/refile_and_grok.1
usr/sbin/rssacd
usr/share/man/man8/rssacd.8
usr/lib/python2.7/dist-packages/*
usr/share/hedgehog/sql/
usr/lib/hedgehog/database_*
usr/lib/hedgehog/datafiles_*
usr/lib/hedgehog/DDL_updates/*
usr/lib/hedgehog/utility_*
etc/init/rssacd.conf
etc/hedgehog/rssacd.conf
