#!/bin/sh

# Add a group for hedgehog so that www-data and hedgehog can be part of it 
# even on a split install
if ! getent group hedgehog > /dev/null; then
  addgroup --system hedgehog
fi

# Make /var/log/hedgehog/ writeable by hedgehog group
# if ! dpkg-statoverride --list /var/log/hedgehog >/dev/null; then
#   dpkg-statoverride --update --add root hedgehog 0775 /var/log/hedgehog >/dev/null 2>/dev/null || true
# fi


#DEBHELPER#
