#!/bin/sh

if test "$1" = "purge"; then
    # this could be wrapped inside debconf question whether to remove the data or not
    rm -rf /etc/hedgehog
    rm -rf /usr/lib/hedgehog
    rm -rf /usr/share/doc/hedgehog
    rm -rf /var/log/hedgehog
    rm -rf /var/lib/hedgehog
    dpkg-statoverride --remove /var/log/hedgehog >/dev/null 2>/dev/null || true
    
    if getent group hedgehog > /dev/null; then
      delgroup --system --only-if-empty hedgehog
    fi
fi

#DEBHELPER#
