# 
# Copyright 2014 Internet Corporation for Assigned Names and Numbers.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Developed by Sinodun IT (www.sinodun.com)
#

#TODO(refactor): Tidy this up so common strings are re-used and we don't need separate node and all_node versions of the same query

prepStmnt <- function(statementNm, dsccon){

    if(class(dsccon) != "try-error"){

        rs <- NULL
        switch(statementNm,
               getdbversion                         = { rs <- try(dbSendQuery(dsccon, "PREPARE getdbversion AS SELECT version FROM dsc.version;"))},
               getpltddcategories                   = { rs <- try(dbSendQuery(dsccon, "PREPARE getpltddcategories AS SELECT DISTINCT ddcategory FROM dsc.plot WHERE ddcategory != '' ORDER BY ddcategory;"))},
               getpltid_ddname                      = { rs <- try(dbSendQuery(dsccon, "PREPARE getpltid_ddname (TEXT) AS SELECT id, ddname FROM dsc.plot WHERE ddcategory=$1 ORDER BY ddname ;"))},
               getpltdetails                        = { rs <- try(dbSendQuery(dsccon, "PREPARE getpltdetails (INTEGER) AS SELECT name, title, description, plot_id FROM dsc.plot WHERE id=$1;"))},
               getsrvrid_display_name               = { rs <- try(dbSendQuery(dsccon, "PREPARE getsrvrid_display_name AS SELECT id, display_name FROM dsc.server ORDER BY display_name;"))},
               getsrvr_display_name_from_id         = { rs <- try(dbSendQuery(dsccon, "PREPARE getsrvr_display_name_from_id AS SELECT display_name FROM dsc.server where id=$1;"))},
               getgroups                            = { rs <- try(dbSendQuery(dsccon, "PREPARE getgroups (INTEGER) AS SELECT DISTINCT region FROM dsc.node WHERE server_id=$1 ORDER BY region;"))},
               getnodes                             = { rs <- try(dbSendQuery(dsccon, "PREPARE getnodes (INTEGER) AS SELECT id, name FROM dsc.node WHERE server_id=$1 ORDER BY name;"))},
               getnodesbyregion                     = { rs <- try(dbSendQuery(dsccon, "PREPARE getnodesbyregion (INTEGER, TEXT) AS SELECT id, name FROM dsc.node WHERE server_id=$1 AND region=$2 ORDER BY name;"))},
               getdatasetids                        = { rs <- try(dbSendQuery(dsccon, "PREPARE getdatasetids (INTEGER) AS SELECT dataset_id FROM dsc.plot WHERE id=$1;"))},
               getdefaultpltid                      = { rs <- try(dbSendQuery(dsccon, "PREPARE getdefaultpltid (TEXT) AS SELECT id FROM dsc.plot WHERE name=$1;"))},

               by_node                              = { rs <- try(dbSendQuery(dsccon, "PREPARE by_node (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, n.name AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d, dsc.node n WHERE d.node_id = n.id AND d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 AND d.node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               by_node_all_nodes                    = { rs <- try(dbSendQuery(dsccon, "PREPARE by_node_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, n.region AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d, dsc.node n WHERE d.node_id = n.id AND d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1                                   = { rs <- try(dbSendQuery(dsccon, "PREPARE f1 (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value)/60.0 AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1_all_nodes                         = { rs <- try(dbSendQuery(dsccon, "PREPARE f1_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value)/60.0 AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1lookupcodes                        = { rs <- try(dbSendQuery(dsccon, "PREPARE f1lookupcodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, CASE WHEN il.name IN ('FormErr', 'NotImp', 'YXDomain', 'YXRRSet', 'NotAuth', 'NotZone', 'BADKEY', 'BADTIME', 'BADMODE', 'BADNAME', 'BADALG', 'BADTRUNC', 'BADVERS') THEN 'Other' WHEN il.name IS NULL THEN 'Other' ELSE il.name END AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key1::text = il.value::text AND il.registry::text = $5 WHERE d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1lookupcodes_all_nodes              = { rs <- try(dbSendQuery(dsccon, "PREPARE f1lookupcodes_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, CASE WHEN il.name IN ('FormErr', 'NotImp', 'YXDomain', 'YXRRSet', 'NotAuth', 'NotZone', 'BADKEY', 'BADTIME', 'BADMODE', 'BADNAME', 'BADALG', 'BADTRUNC', 'BADVERS') THEN 'Other' WHEN il.name IS NULL THEN 'Other' ELSE il.name END AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key1::text = il.value::text AND il.registry::text = $5 WHERE d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1lookupcodesnoquery                 = { rs <- try(dbSendQuery(dsccon, "PREPARE f1lookupcodesnoquery (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, CASE WHEN il.name IS NULL THEN 'Other' ELSE il.name END AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key1::text = il.value::text AND il.registry::text = $5 WHERE d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) AND d.key1 !='Query' GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1lookupcodesnoquery_all_nodes       = { rs <- try(dbSendQuery(dsccon, "PREPARE f1lookupcodesnoquery_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, CASE WHEN il.name IS NULL THEN 'Other' ELSE il.name END AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key1::text = il.value::text AND il.registry::text = $5 WHERE d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 AND d.key1 !='Query' GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1noclr                              = { rs <- try(dbSendQuery(dsccon, "PREPARE f1noclr (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value)/60.0 AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND node_id = ANY (string_to_array($5, ',')::integer[]) AND key1 !='clr' GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1noclr_all_nodes                    = { rs <- try(dbSendQuery(dsccon, "PREPARE f1noclr_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value)/60.0 AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND key1 !='clr' GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1count                              = { rs <- try(dbSendQuery(dsccon, "PREPARE f1count (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value) AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1count_all_nodes                    = { rs <- try(dbSendQuery(dsccon, "PREPARE f1count_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value) AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1nonormal                           = { rs <- try(dbSendQuery(dsccon, "PREPARE f1nonormal (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value)/60.0 AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND node_id = ANY (string_to_array($5, ',')::integer[]) AND key1 !='normal' GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f1nonormal_all_nodes                 = { rs <- try(dbSendQuery(dsccon, "PREPARE f1nonormal_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value)/60.0 AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND key1 !='normal' GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f2mergekeys                          = { rs <- try(dbSendQuery(dsccon, "PREPARE f2mergekeys (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, d.key1 || ':' || key2 AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d WHERE d.key1 != 'else' AND d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 AND d.node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f2mergekeys_all_nodes                = { rs <- try(dbSendQuery(dsccon, "PREPARE f2mergekeys_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, d.key1 || ':' || key2 AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d WHERE d.key1 != 'else' AND d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f2mergekeys_lookup                   = { rs <- try(dbSendQuery(dsccon, "PREPARE f2mergekeys_lookup (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, d.key1 || ':' || CASE WHEN il.name IS NULL THEN 'Other' ELSE il.name END AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key2::text = il.value::text AND il.registry::text='qtype' WHERE d.key1 != 'else' AND d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 AND d.node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f2mergekeys_lookup_all_nodes         = { rs <- try(dbSendQuery(dsccon, "PREPARE f2mergekeys_lookup_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, d.key1 || ':' || CASE WHEN il.name IS NULL then 'Other' ELSE il.name END AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key2::text = il.value::text AND il.registry::text='qtype' WHERE d.key1 != 'else' AND d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f2mergekeys_lookup_key1              = { rs <- try(dbSendQuery(dsccon, "PREPARE f2mergekeys_lookup_key1 (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, il.name || ':' || key2 AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d, iana_lookup il WHERE il.registry::text='qtype' AND key1::text = il.value::text AND d.key1 != 'else' AND d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 AND d.node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f2mergekeys_lookup_key1_all_nodes    = { rs <- try(dbSendQuery(dsccon, "PREPARE f2mergekeys_lookup_key1_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT d.starttime AS sx, il.name || ':' || key2 AS skey, sum(d.value)/60.0 AS sy FROM dsc.data d, iana_lookup il WHERE il.registry::text='qtype' AND key1::text = il.value::text AND d.key1 != 'else' AND d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f2sumkey2values                      = { rs <- try(dbSendQuery(dsccon, "PREPARE f2sumkey2values (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value)/60.0 AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               f2sumkey2values_all_nodes            = { rs <- try(dbSendQuery(dsccon, "PREPARE f2sumkey2values_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS select to_timestamp((extract(epoch from sq.sx)::int / (extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int )*(extract(epoch from $4::timestamp - $3::timestamp + interval '1 minute')/1440)::int) AS x, sq.skey as key, avg(sq.sy) as y from (SELECT starttime AS sx, key1 AS skey, sum(value)/60.0 AS sy FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 GROUP BY sx, skey) as sq GROUP BY x, key;"))},
               format3                              = { rs <- try(dbSendQuery(dsccon, "PREPARE format3 (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT substring(key2 FROM '(^([0-9a-f]{1,4}:[0-9a-f]{1,4}:)|^([0-9]{1,3}.))') AS x, sum(value)/$1 AS y FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND node_id = ANY (string_to_array($6, ',')::integer[]) AND key2 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY x ORDER BY y DESC LIMIT 40;"))},
               format3_all_nodes                    = { rs <- try(dbSendQuery(dsccon, "PREPARE format3_all_nodes (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT substring(key2 FROM '(^([0-9a-f]{1,4}:[0-9a-f]{1,4}:)|^([0-9]{1,3}.))') AS x, sum(value)/$1 AS y FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND key2 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY x ORDER BY y DESC LIMIT 40;"))},
               qtype_vs_tld                         = { rs <- try(dbSendQuery(dsccon, "PREPARE qtype_vs_tld (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT d.key1 AS x, CASE WHEN il.name IS NULL THEN 'Other' ELSE il.name END AS key, sum(d.value)/$1 AS y FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key2::text = il.value::text AND il.registry = 'qtype' WHERE d.server_id=$2 AND d.plot_id=$3 AND d.starttime>=$4 AND d.starttime<=$5 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) AND d.key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') AND d.key1 IN (SELECT key1 FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND node_id = ANY (string_to_array($6, ',')::integer[]) AND key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY key1 ORDER BY sum(value)/$1 DESC LIMIT 40) GROUP BY x, key;"))},
               qtype_vs_tld_all_nodes               = { rs <- try(dbSendQuery(dsccon, "PREPARE qtype_vs_tld_all_nodes (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT d.key1 AS x, CASE WHEN il.name IS NULL THEN 'Other' ELSE il.name END AS key, sum(d.value)/$1 AS y FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key2::text = il.value::text AND il.registry = 'qtype' WHERE d.server_id=$2 AND d.plot_id=$3 AND d.starttime>=$4 AND d.starttime<=$5 AND d.key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') AND d.key1 IN (SELECT key1 FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY key1 ORDER BY sum(value)/$1 DESC LIMIT 40) GROUP BY x, key;"))},
               client_addr_vs_rcode_accum           = { rs <- try(dbSendQuery(dsccon, "PREPARE client_addr_vs_rcode_accum (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT substring(d.key1 FROM'(^([0-9a-f]{1,4}:[0-9a-f]{1,4}:)|^([0-9]{1,3}.))' ) AS x, il.name AS key, sum(d.value)/$1 As y FROM dsc.data d, iana_lookup il WHERE server_id=$2 AND d.plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND node_id = ANY (string_to_array($6, ',')::integer[]) AND d.key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') AND il.registry = 'rcode' AND d.key2::text = il.value::text AND substring(key1 FROM '(^([0-9a-f]{1,4}:[0-9a-f]{1,4}:)|^([0-9]{1,3}.))') IN (SELECT substring(key1 FROM '(^([0-9a-f]{1,4}:[0-9a-f]{1,4}:)|^([0-9]{1,3}.))')::text AS k1 FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND node_id = ANY (string_to_array($6, ',')::integer[]) AND key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY k1 ORDER BY sum(value)/$1 DESC LIMIT 40) GROUP BY x, key;"))},
               client_addr_vs_rcode_accum_all_nodes = { rs <- try(dbSendQuery(dsccon, "PREPARE client_addr_vs_rcode_accum_all_nodes (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT substring(d.key1 FROM '(^([0-9a-f]{1,4}:[0-9a-f]{1,4}:)|^([0-9]{1,3}.))') AS x, il.name AS key, sum(d.value)/$1 As y FROM dsc.data d, iana_lookup il WHERE server_id=$2 AND d.plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND d.key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') AND il.registry = 'rcode' AND d.key2::text = il.value::text AND d.key2::text = il.value::text AND substring(key1 FROM '(^([0-9a-f]{1,4}:[0-9a-f]{1,4}:)|^([0-9]{1,3}.))') IN (SELECT substring(key1 FROM '(^([0-9a-f]{1,4}:[0-9a-f]{1,4}:)|^([0-9]{1,3}.))')::text AS k1 FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY k1 ORDER BY sum(value)/$1 DESC LIMIT 40) GROUP BY x, key;"))},
               qtype_vs_qnamelen                    = { rs <- try(dbSendQuery(dsccon, "PREPARE qtype_vs_qnamelen (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT il.name AS key, cast(d.key2 AS int) AS x, sum(d.value) AS y FROM dsc.data d, iana_lookup il WHERE server_id=$1 AND d.plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND node_id = ANY (string_to_array($5, ',')::integer[]) AND d.key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') AND il.registry = 'qtype' AND d.key1::text = il.value::text AND cast(d.key2 AS int) < 100 GROUP BY key, x;"))},
               qtype_vs_qnamelen_all_nodes          = { rs <- try(dbSendQuery(dsccon, "PREPARE qtype_vs_qnamelen_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT il.name AS key, cast(d.key2 AS int) AS x, sum(d.value) AS y FROM dsc.data d, iana_lookup il WHERE server_id=$1 AND d.plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND d.key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') AND il.registry = 'qtype' AND d.key1::text = il.value::text AND cast(d.key2 AS int) < 100 GROUP BY key, x;"))},
               rcode_vs_replylen                    = { rs <- try(dbSendQuery(dsccon, "PREPARE rcode_vs_replylen (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT il.name AS key, key2::integer AS x, d.value AS y FROM dsc.data d, iana_lookup il WHERE server_id=$1 AND d.plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND node_id = ANY (string_to_array($5, ',')::integer[]) AND il.registry = 'rcode' AND d.key1::text = il.value::text AND key2::integer < 1000;"))},
               rcode_vs_replylen_all_nodes          = { rs <- try(dbSendQuery(dsccon, "PREPARE rcode_vs_replylen_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT il.name AS key, key2::integer AS x, d.value AS y FROM dsc.data d, iana_lookup il WHERE server_id=$1 AND d.plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND il.registry = 'rcode' AND d.key1::text = il.value::text AND key2::integer < 1000;"))},
               rcode_vs_replylen_big                = { rs <- try(dbSendQuery(dsccon, "PREPARE rcode_vs_replylen_big (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT il.name AS key, key2::integer AS x, d.value AS y FROM dsc.data d, iana_lookup il WHERE server_id=$1 AND d.plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND node_id = ANY (string_to_array($5, ',')::integer[]) AND il.registry = 'rcode' AND d.key1::text = il.value::text AND key2::integer >= 1000;"))},
               rcode_vs_replylen_big_all_nodes      = { rs <- try(dbSendQuery(dsccon, "PREPARE rcode_vs_replylen_big_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT il.name AS key, key2::integer AS x, d.value AS y FROM dsc.data d, iana_lookup il WHERE server_id=$1 AND d.plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND il.registry = 'rcode' AND d.key1::text = il.value::text AND key2::integer >= 1000;"))},               client_subnet2_accum                 = { rs <- try(dbSendQuery(dsccon, "PREPARE client_subnet2_accum (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT substring(key1 FROM '^([0-9]*.)|.*:.*') AS x, key2 AS key, sum(value)/$1 As y FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND node_id = ANY (string_to_array($6, ',')::integer[]) AND substring(key1 FROM '^([0-9]*.)|.*:.*') IN (SELECT substring(key1 FROM '^([0-9]*.)|.*:.*')::text AS k1 FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND node_id = ANY (string_to_array($6, ',')::integer[]) AND key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY k1 ORDER BY sum(value)/$1 DESC LIMIT 40) GROUP BY x, key;"))},
               client_subnet2_accum_all_nodes       = { rs <- try(dbSendQuery(dsccon, "PREPARE client_subnet2_accum_all_nodes (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT substring(key1 FROM '^([0-9]*.)|.*:.*') AS x, key2 AS key, sum(value)/$1 As y FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND substring(key1 FROM '^([0-9]*.)|.*:.*') IN (SELECT substring(key1 FROM '^([0-9]*.)|.*:.*')::text AS k1 FROM dsc.data WHERE server_id=$2 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY k1 ORDER BY sum(value)/$1 DESC LIMIT 40) GROUP BY x, key;"))},
               dns_ip_version_vs_qtype              = { rs <- try(dbSendQuery(dsccon, "PREPARE dns_ip_version_vs_qtype (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT d.key1 AS x, CASE WHEN il.name IS NULL THEN 'Other' ELSE il.name END AS key, sum(d.value)/$1 As y FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key2::text = il.value::text AND il.registry = 'qtype' WHERE d.server_id=$2 AND d.plot_id=$3 AND d.starttime>=$4 AND d.starttime<=$5 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) AND d.key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY x, key ORDER BY y DESC;"))},
               dns_ip_version_vs_qtype_all_nodes    = { rs <- try(dbSendQuery(dsccon, "PREPARE dns_ip_version_vs_qtype_all_nodes (REAL, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT d.key1 AS x, CASE WHEN il.name IS NULL THEN 'Other' ELSE il.name END AS key, sum(d.value)/$1 As y FROM dsc.data d LEFT OUTER JOIN iana_lookup il ON d.key2::text = il.value::text AND il.registry = 'qtype' WHERE d.server_id=$2 AND d.plot_id=$3 AND d.starttime>=$4 AND d.starttime<=$5 AND d.key1 NOT IN ('-:SKIPPED_SUM:-', '-:SKIPPED:-') GROUP BY x, key ORDER BY y DESC;"))},

               traffic_volume                       = { rs <- try(dbSendQuery(dsccon, "PREPARE traffic_volume (INTEGER, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT starttime AS x, 'dns-' || key1 || '-queries-received-' || lower(key2) AS key, sum(value) AS y FROM dsc.data d WHERE server_id=$1 AND plot_id=$2 AND starttime>=$4 AND starttime<=$5 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) GROUP BY x, key UNION SELECT starttime AS x, 'dns-' || key1 || '-responses-sent-' || lower(key2) AS key, sum(value) AS y FROM dsc.data d WHERE server_id=$1 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) GROUP BY x, key;"))},
               traffic_volume_all_nodes             = { rs <- try(dbSendQuery(dsccon, "PREPARE traffic_volume_all_nodes (INTEGER, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT starttime AS x, 'dns-' || key1 || '-queries-received-' || lower(key2) AS key, sum(value) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$4 AND starttime<=$5 GROUP BY x, key UNION SELECT starttime AS x, 'dns-' || key1 || '-responses-sent-' || lower(key2) AS key, sum(value) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 GROUP BY x, key;"))},
               # Following two statements are used to generate yaml data, but not for a visible plot
               traffic_sizes                        = { rs <- try(dbSendQuery(dsccon, "PREPARE traffic_sizes (INTEGER, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT key1 || '-request-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data d WHERE server_id=$1 AND plot_id=$2 AND starttime>=$4 AND starttime<=$5  AND d.node_id = ANY (string_to_array($6, ',')::integer[]) GROUP BY key, x UNION SELECT key1 || '-response-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data d WHERE server_id=$1 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5  AND d.node_id = ANY (string_to_array($6, ',')::integer[]) GROUP BY key, x ORDER BY x;"))},
               traffic_sizes_all_nodes              = { rs <- try(dbSendQuery(dsccon, "PREPARE traffic_sizes_all_nodes (INTEGER, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT key1 || '-request-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$4 AND starttime<=$5  GROUP BY key, x UNION SELECT key1 || '-response-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 GROUP BY key, x ORDER BY x;"))},
               traffic_sizes_small                  = { rs <- try(dbSendQuery(dsccon, "PREPARE traffic_sizes_small (INTEGER, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT key1 || '-request-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data d WHERE server_id=$1 AND plot_id=$2 AND starttime>=$4 AND starttime<=$5 AND key2::integer < 1000 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) GROUP BY key, x UNION SELECT key1 || '-response-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data d WHERE server_id=$1 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND key2::integer < 1000 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) GROUP BY key, x ORDER BY x;"))},
               traffic_sizes_small_all_nodes        = { rs <- try(dbSendQuery(dsccon, "PREPARE traffic_sizes_small_all_nodes (INTEGER, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT key1 || '-request-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$4 AND starttime<=$5 AND key2::integer < 1000 GROUP BY key, x UNION SELECT key1 || '-response-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND key2::integer < 1000 GROUP BY key, x ORDER BY x;"))},
               traffic_sizes_big                    = { rs <- try(dbSendQuery(dsccon, "PREPARE traffic_sizes_big (INTEGER, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT key1 || '-request-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data d WHERE server_id=$1 AND plot_id=$2 AND starttime>=$4 AND starttime<=$5 AND key2::integer >= 1000 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) GROUP BY key, x UNION SELECT key1 || '-response-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data d WHERE server_id=$1 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND key2::integer >= 1000 AND d.node_id = ANY (string_to_array($6, ',')::integer[]) GROUP BY key, x ORDER BY x;"))},
               traffic_sizes_big_all_nodes          = { rs <- try(dbSendQuery(dsccon, "PREPARE traffic_sizes_big_all_nodes (INTEGER, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT key1 || '-request-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$4 AND starttime<=$5 AND key2::integer >= 1000 GROUP BY key, x UNION SELECT key1 || '-response-sizes' AS key, ((key2::integer/16) * 16) + 7.5 AS x, sum(value) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$3 AND starttime>=$4 AND starttime<=$5 AND key2::integer >= 1000 GROUP BY key, x ORDER BY x;"))},
               rcode_volume                         = { rs <- try(dbSendQuery(dsccon, "PREPARE rcode_volume (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT d.starttime AS x, d.key1 AS key, sum(d.value) AS y FROM dsc.data d WHERE d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 AND d.node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY x, key;"))},
               rcode_volume_all_nodes               = { rs <- try(dbSendQuery(dsccon, "PREPARE rcode_volume_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT d.starttime AS x, d.key1 AS key, sum(d.value) AS y FROM dsc.data d WHERE d.server_id=$1 AND d.plot_id=$2 AND d.starttime>=$3 AND d.starttime<=$4 GROUP BY x, key;"))},
               unique_sources_raw                   = { rs <- try(dbSendQuery(dsccon, "PREPARE unique_sources_raw (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT key1 as x, count(key2) AS y FROM dsc.data as d WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND d.node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY x UNION SELECT 'IPv6/64' as x, count(*) as y from (SELECT substring(key2 FROM '(^([0-9a-f]{1,4}:{0,1}[0-9a-f]{0,4}:{0,1}[0-9a-f]{0,4}:{0,1}[0-9a-f]{0,4}))') as subnet FROM dsc.data as d WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND key1='IPv6' AND d.node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY subnet) AS sq ORDER BY y DESC;"))},
               unique_sources_raw_all_nodes         = { rs <- try(dbSendQuery(dsccon, "PREPARE unique_sources_raw_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT key1 as x, count(key2) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 GROUP BY x UNION SELECT 'IPv6/64' as x, count(*) as y from (SELECT substring(key2 FROM '(^([0-9a-f]{1,4}:{0,1}[0-9a-f]{0,4}:{0,1}[0-9a-f]{0,4}:{0,1}[0-9a-f]{0,4}))') as subnet FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND key1='IPv6' GROUP BY subnet) AS sq ORDER BY y DESC;"))},
               unique_sources                       = { rs <- try(dbSendQuery(dsccon, "PREPARE unique_sources (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT) AS SELECT key1 as x, sum(value) AS y FROM dsc.data as d WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 AND d.node_id = ANY (string_to_array($5, ',')::integer[]) GROUP BY x order by y DESC;"))},
               unique_sources_all_nodes             = { rs <- try(dbSendQuery(dsccon, "PREPARE unique_sources_all_nodes (INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ) AS SELECT key1 as x, sum(value) AS y FROM dsc.data WHERE server_id=$1 AND plot_id=$2 AND starttime>=$3 AND starttime<=$4 GROUP BY x order by y desc;"))}

        )

        if(class(rs) == "try-error"){
            system(paste('logger -p user.crit database failed to load prepared statement name: "', statementNm, '" FROM dbconn.R', sep=""))
            return(FALSE)
        }else{
            return(TRUE)
        }
    }else{
        return(FALSE)
    }
}
