#!/bin/bash
# 
# Copyright 2015 Internet Corporation for Assigned Names and Numbers.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Developed by Sinodun IT (www.sinodun.com)
#

# 
# File:   hh_database_create
#

DB_NAME=hedgehog
DB_OWNER=hedgehog
DB_READER=www-data

usage () {
	echo
	echo "Create database and roles/users."
	echo
	echo "Usage: $(basename $0) options"
	echo
	echo "Supported options:"
	echo "  -o Owner of the database  (Default: $DB_OWNER)"
	echo "  -r Reader of the database (Default: $DB_READER) Typically the same user that the web server runs as."
	echo "  -n Name of the database   (Default: $DB_NAME)"
	echo "  -h Show this help"
	echo
	echo "In the 'database' section of hedgehog.yaml you should set the same values"
  
  exit 1
}

while getopts ":o:r:n:h" opt; do
    case $opt in
        o  ) DB_OWNER=$OPTARG ;;
        r  ) DB_READER=$OPTARG ;;
        n  ) DB_NAME=$OPTARG ;;
        h  ) usage ;;
        \? ) usage ;;
    esac
done

DB_EXISTS=$(psql -tlq | cut -d \| -f 1 | grep -w $DB_NAME)
[ "x$DB_EXISTS" != "x" ] && echo "The $DB_NAME Database exists. If you want to overwrite it then drop it manually and re-run this script" && exit 1

psql <<EOF
CREATE USER "$DB_OWNER";
CREATE ROLE hh_read;
CREATE ROLE hh_write;
CREATE DATABASE "$DB_NAME"
  WITH OWNER = "$DB_OWNER"
  ENCODING = 'UTF8'
  TABLESPACE = pg_default
  CONNECTION LIMIT = -1;
CREATE USER "$DB_READER";
GRANT hh_read TO "$DB_READER";
ALTER USER "$DB_READER" SET search_path TO dsc;
ALTER USER "$DB_OWNER" SET search_path TO dsc;
EOF

echo
echo "Please add $DB_OWNER and $DB_READER to pg_hba.conf, set passwords etc."
